c.url.searchengines = {
    'DEFAULT':  'https://google.com/search?hl=en&q={}',
    '!g':       'https://google.com/search?hl=en&q={}',
    '!a':       'https://www.amazon.com/s?k={}',
    '!d':       'https://duckduckgo.com/?ia=web&q={}',
    '!dd':      'https://thefreedictionary.com/{}',
    '!e':       'https://www.ebay.com/sch/i.html?_nkw={}',
    '!fb':      'https://www.facebook.com/s.php?q={}',
    '!gh':      'https://github.com/search?o=desc&q={}&s=stars',
    '!gist':    'https://gist.github.com/search?q={}',
    '!gi':      'https://www.google.com/search?tbm=isch&q={}&tbs=imgo:1',
    '!gn':      'https://news.google.com/search?q={}',
    '!ig':      'https://www.instagram.com/explore/tags/{}',
    '!m':       'https://www.google.com/maps/search/{}',
    '!p':       'https://pry.sh/{}',
    '!r':       'https://www.reddit.com/search?q={}',
    '!sd':      'https://slickdeals.net/newsearch.php?q={}&searcharea=deals&searchin=first',
    '!t':       'https://www.thesaurus.com/browse/{}',
    '!tw':      'https://twitter.com/search?q={}',
    '!w':       'https://en.wikipedia.org/wiki/{}',
    '!yelp':    'https://www.yelp.com/search?find_desc={}',
    '!yt':      'https://www.youtube.com/results?search_query={}'
}

config.set('colors.completion.category.border.bottom', '#161320')
config.set('colors.completion.category.border.top', '#161320')
config.set('colors.completion.category.fg', '#161320')
config.set('colors.completion.even.bg', '#1A1826')
config.set('colors.completion.fg', ['#D9E0EE', '#D9E0EE', '#D9E0EE'])
config.set('colors.completion.item.selected.bg', '#161320')
config.set('colors.completion.item.selected.border.bottom', '#D9E0EE')
config.set('colors.completion.item.selected.border.top', '#D9E0EE')
config.set('colors.completion.item.selected.fg', '#D9E0EE')
config.set('colors.completion.item.selected.match.fg', '#F5E0DC')
config.set('colors.completion.match.fg', '#F5E0DC')
config.set('colors.completion.odd.bg', '#1E1E2E')
config.set('colors.completion.scrollbar.bg', '#161320')
config.set('colors.completion.scrollbar.fg', '#575268')
config.set('colors.contextmenu.disabled.fg', '#C3BAC6')
config.set('colors.contextmenu.menu.bg', '#161320')
config.set('colors.contextmenu.menu.fg', '#D9E0EE')
config.set('colors.contextmenu.selected.bg', '#1E1E2E')
config.set('colors.contextmenu.selected.fg', '#F5E0DC')
config.set('colors.downloads.bar.bg', '#161320')
config.set('colors.downloads.error.bg', '#F28FAD')
config.set('colors.downloads.error.fg', '#D9E0EE')
config.set('colors.downloads.stop.bg', '#ABE9B3')
config.set('colors.downloads.stop.fg', '#D9E0EE')
config.set('colors.hints.bg', '#161320')
config.set('colors.hints.fg', '#D9E0EE')
config.set('colors.hints.match.fg', '#F5E0DC')
config.set('colors.keyhint.bg', '#1A1826')
config.set('colors.keyhint.fg', '#D9E0EE')
config.set('colors.keyhint.suffix.fg', '#F5E0DC')
config.set('colors.messages.error.bg', '#F28FAD')
config.set('colors.messages.error.border', '#F28FAD')
config.set('colors.downloads.bar.bg', '#161320')
config.set('colors.downloads.error.bg', '#F28FAD')
config.set('colors.downloads.error.fg', '#D9E0EE')
config.set('colors.downloads.stop.bg', '#ABE9B3')
config.set('colors.downloads.stop.fg', '#D9E0EE')
config.set('colors.hints.bg', '#161320')
config.set('colors.hints.fg', '#D9E0EE')
config.set('colors.hints.match.fg', '#F5E0DC')
config.set('colors.keyhint.bg', '#1A1826')
config.set('colors.keyhint.fg', '#D9E0EE')
config.set('colors.keyhint.suffix.fg', '#F5E0DC')
config.set('colors.messages.error.border', '#E8A2AF')
config.set('colors.messages.error.fg', '#D9E0EE')
config.set('colors.messages.info.bg', '#161320')
config.set('colors.messages.info.border', '#302D41')
config.set('colors.messages.info.fg', '#D9E0EE')
config.set('colors.messages.warning.bg', '#F8BD96')
config.set('colors.messages.warning.border', '#FAE3B0')
config.set('colors.messages.warning.fg', '#161320')
config.set('colors.prompts.bg', '#161320')
config.set('colors.prompts.border', '1px solid #302D41')
config.set('colors.prompts.fg', '#D9E0EE')
config.set('colors.prompts.selected.bg', '#302D41')
config.set('colors.prompts.selected.fg', '#D9E0EE')
config.set('colors.statusbar.caret.bg', '#302D41')
config.set('colors.statusbar.caret.fg', '#D9E0EE')
config.set('colors.statusbar.caret.selection.bg', '#1E1E2E')
config.set('colors.statusbar.caret.selection.fg', '#F5E0DC')
config.set('colors.statusbar.caret.selection.bg', '#1E1E2E')
config.set('colors.statusbar.caret.selection.fg', '#F5E0DC')
config.set('colors.statusbar.command.bg', '#161320')
config.set('colors.statusbar.command.fg', '#D9E0EE')
config.set('colors.statusbar.command.private.bg', '#161320')
config.set('colors.statusbar.command.private.fg', '#D9E0EE')
config.set('colors.statusbar.insert.bg', '#1E1E2E')
config.set('colors.statusbar.insert.fg', '#D9E0EE')
config.set('colors.statusbar.normal.bg', '#161320')
config.set('colors.statusbar.normal.fg', '#D9E0EE')
config.set('colors.statusbar.passthrough.bg', '#302D41')
config.set('colors.statusbar.passthrough.fg', '#D9E0EE')
config.set('colors.statusbar.private.bg', '#161320')
config.set('colors.statusbar.private.fg', '#C9CBFF')
config.set('colors.statusbar.progress.bg', '#C9CBFF')
config.set('colors.statusbar.url.error.fg', '#F2CDCD')
config.set('colors.statusbar.url.fg', '#D9E0EE')
config.set('colors.statusbar.url.hover.fg', '#96CDFB')
config.set('colors.statusbar.url.success.http.fg', '#D9E0EE')
config.set('colors.statusbar.url.success.https.fg', '#ABE9B3')
config.set('colors.statusbar.url.warn.fg', '#FAE3B0')
config.set('colors.tabs.bar.bg', '#161320')
config.set('colors.tabs.even.bg', '#1E1E2E')
config.set('colors.tabs.even.fg', '#D9E0EE')
config.set('colors.tabs.odd.bg', '#302D41')
config.set('colors.tabs.odd.fg', '#D9E0EE')
config.set('colors.tabs.pinned.even.bg', '#ABE9B3')
config.set('colors.tabs.pinned.even.fg', '#D9E0EE')
config.set('colors.tabs.pinned.odd.bg', '#1A1826')
config.set('colors.tabs.pinned.odd.fg', '#D9E0EE')
config.set('colors.tabs.pinned.selected.even.bg', '#161320')
config.set('colors.tabs.pinned.selected.even.fg', '#D9E0EE')
config.set('colors.tabs.pinned.selected.odd.bg', '#161320')
config.set('colors.tabs.pinned.selected.odd.fg', '#D9E0EE')
config.set('colors.tabs.selected.even.bg', '#161320')
config.set('colors.tabs.selected.even.fg', '#F5E0DC')
config.set('colors.tabs.selected.odd.bg', '#161320')
config.set('colors.tabs.selected.odd.fg', '#F5E0DC')

#config.set('content.unknown_url_scheme_policy', 'allow-all')

config.load_autoconfig()
