#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# audio
#/usr/bin/pipewire & /usr/bin/pipewire-pulse & /usr/bin/pipewire-media-session &
gentoo-pipewire-launcher &

# keybind handling daemon
export SXHKD_SHELL=sh
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc &

# all bspwm workspaces 
bspc monitor -d  爵    﫢 ﭧ
# start compositor
picom --experimental-backends --config ~/.config/picom/picom.conf &
# bash $SCRIPTPATH/scripts/blur_wallpaper.sh &

# notifications
dunst -c ~/.config/dunst/dunstrc &

# static wallpaper
feh --bg-scale ~/wallpapers/Forgotten-Land-day.webp & 

# general settings for bspwm
bspc config focused_border_color \#6E6C7E
bspc config active_border_color  \#575268
bspc config normal_border_color  \#575268
bspc config border_width                1
bspc config window_gap                 16
bspc config split_ratio               0.6
bspc config ignore_ewmh_struts       true
bspc config top_padding                35

# polybar
polybar -r -c ~/.config/polybar/polybar.conf main &

# tiled firefox fix 
bspc rule -a firefox state=tiled
bspc rule -a firefox-nightly state=tiled
